<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
  public function run(): void
  {
    DB::table('products')->insert([
      [
        'product_name' => 'Margherita',
        'product_description' => 'Margherita',
        'qty' => 150,
        'price' => 29.99,
        'star' => 4.5,
        'time_value' => 60,
        'product_image' => 'storage/products/margherita.jpg',
        'category_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Bacon and Cheese Heaven',
        'product_description' => 'Bacon and Cheese Heaven',
        'qty' => 75,
        'price' => 89.99,
        'star' => 4.7,
        'time_value' => 120,
        'product_image' => 'storage/products/bacon_and_cheese_heaven.jpg',
        'category_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Bacon-Wrapped Filet Mignon',
        'product_description' => 'Bacon-Wrapped Filet Mignon',
        'qty' => 300,
        'price' => 19.99,
        'star' => 4.0,
        'time_value' => 30,
        'product_image' => 'storage/products/bacon_wrapped_filet_mignon.jpg',
        'category_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'BBQ Chicken Delight',
        'product_description' => 'BBQ Chicken Delight',
        'qty' => 120,
        'price' => 59.99,
        'star' => 4.6,
        'time_value' => 90,
        'product_image' => 'storage/products/bbq_chicken_delight.jpg',
        'category_id' => 3,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'BBQ Ranch Delight',
        'product_description' => 'BBQ Ranch Delight',
        'qty' => 200,
        'price' => 39.99,
        'star' => 4.3,
        'time_value' => 60,
        'product_image' => 'storage/products/bbq_ranch_delight.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Beef Stir-Fry with Broccoli',
        'product_description' => 'Beef Stir-Fry with Broccoli',
        'qty' => 85,
        'price' => 149.99,
        'star' => 4.8,
        'time_value' => 150,
        'product_image' => 'storage/products/beef_stir_fry_with_broccoli.jpg',
        'category_id' => 5,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Berry Blast Smoothie',
        'product_description' => 'Berry Blast Smoothie',
        'qty' => 220,
        'price' => 99.99,
        'star' => 4.7,
        'time_value' => 90,
        'product_image' => 'storage/products/berry_blast_smoothie.jpg',
        'category_id' => 6,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'California Roll',
        'product_description' => 'California Roll',
        'qty' => 100,
        'price' => 79.99,
        'star' => 4.5,
        'time_value' => 100,
        'product_image' => 'storage/products/california_roll.jpg',
        'category_id' => 7,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Chicago Style Hot Dog',
        'product_description' => 'Chicago Style Hot Dog',
        'qty' => 250,
        'price' => 25.99,
        'star' => 4.2,
        'time_value' => 45,
        'product_image' => 'storage/products/chicago_style_hot_dog.jpg',
        'category_id' => 8,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Chicken Avocado Bliss',
        'product_description' => 'Chicken Avocado Bliss',
        'qty' => 50,
        'price' => 299.99,
        'star' => 4.6,
        'time_value' => 180,
        'product_image' => 'storage/products/chicken_avocado_bliss.jpg',
        'category_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Chili Cheese Dog',
        'product_description' => 'Chili Cheese Dog',
        'qty' => 180,
        'price' => 24.99,
        'star' => 4.4,
        'time_value' => 70,
        'product_image' => 'storage/products/chili_cheese_dog.jpg',
        'category_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Classic Beef Burger',
        'product_description' => 'Classic Beef Burger',
        'qty' => 500,
        'price' => 9.99,
        'star' => 4.1,
        'time_value' => 20,
        'product_image' => 'storage/products/classic_beef_burger.jpg',
        'category_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Classic Beef Hot Dog',
        'product_description' => 'Classic Beef Hot Dog',
        'qty' => 40,
        'price' => 199.99,
        'star' => 4.8,
        'time_value' => 180,
        'product_image' => 'storage/products/classic_beef_hot_dog.jpg',
        'category_id' => 3,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Coconut Water',
        'product_description' => 'Coconut Water',
        'qty' => 300,
        'price' => 14.99,
        'star' => 4.2,
        'time_value' => 30,
        'product_image' => 'storage/products/coconut_water.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Dragon Roll',
        'product_description' => 'Dragon Roll',
        'qty' => 200,
        'price' => 19.99,
        'star' => 4.3,
        'time_value' => 60,
        'product_image' => 'storage/products/dragon_roll.jpg',
        'category_id' => 5,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Espresso Martini',
        'product_description' => 'Espresso Martini',
        'qty' => 150,
        'price' => 34.99,
        'star' => 4.4,
        'time_value' => 80,
        'product_image' => 'storage/products/espresso_martini.jpg',
        'category_id' => 6,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Four Cheese Delight',
        'product_description' => 'Four Cheese Delight',
        'qty' => 120,
        'price' => 39.99,
        'star' => 4.5,
        'time_value' => 100,
        'product_image' => 'storage/products/four_cheese_delight.jpg',
        'category_id' => 7,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Fresh Orange Juice',
        'product_description' => 'Fresh Orange Juice',
        'qty' => 200,
        'price' => 49.99,
        'star' => 4.7,
        'time_value' => 120,
        'product_image' => 'storage/products/fresh_orange_juice.jpg',
        'category_id' => 8,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Garlic Parmesan Chicken',
        'product_description' => 'Garlic Parmesan Chicken',
        'qty' => 80,
        'price' => 79.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/garlic_parmesan_chicken.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Green Tea Latte',
        'product_description' => 'Green Tea Latte',
        'qty' => 80,
        'price' => 79.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/green_tea_latte.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Grilled Ribeye Steak',
        'product_description' => 'Grilled Ribeye Steak',
        'qty' => 80,
        'price' => 79.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/grilled_ribeye_steak.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Green Tea Latte',
        'product_description' => 'Green Tea Latte',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/green_tea_latte.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Grilled Ribeye Steak',
        'product_description' => 'Grilled Ribeye Steak',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/grilled_ribeye_steak.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Hawaiian BBQ Dog',
        'product_description' => 'Hawaiian BBQ Dog',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/hawaiian_bbq_dog.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Hawaiian Paradise',
        'product_description' => 'Hawaiian Paradise',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/hawaiian_paradise.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Honey Mustard Glazed Tenders',
        'product_description' => 'Honey Mustard Glazed Tenders',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/honey_mustard_glazed_tenders.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Iced Caramel Macchiato',
        'product_description' => 'Iced Caramel Macchiato',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/iced_caramel_macchiato.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Kimchi Hot Dog',
        'product_description' => 'Kimchi Hot Dog',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/kimchi_hot_dog.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Korean BBQ Short Ribs',
        'product_description' => 'Korean BBQ Short Ribs',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/korean_bbq_short_ribs.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Korean Fried Chicken',
        'product_description' => 'Korean Fried Chicken',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/korean_fried_chicken.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Lemon Pepper Chicken',
        'product_description' => 'Lemon Pepper Chicken',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/lemon_pepper_chicken.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Mango Tango Slush',
        'product_description' => 'Mango Tango Slush',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/mango_tango_slush.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Margherita Flatbread',
        'product_description' => 'Margherita Flatbread',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/margherita_flatbread.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Margherita',
        'product_description' => 'Margherita',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/margherita.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Reuben Style Hot Dog',
        'product_description' => 'Reuben Style Hot Dog',
        'qty' => 90,
        'price' => 89.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/reuben_style_hot_dog.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Salmon Nigiri',
        'product_description' => 'Salmon Nigiri',
        'qty' => 70,
        'price' => 69.99,
        'star' => 3.6,
        'time_value' => 150,
        'product_image' => 'storage/products/salmon_nigiri.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Sashimi Platter',
        'product_description' => 'Sashimi Platter',
        'qty' => 90,
        'price' => 59.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/sashimi_platter.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Shrimp Scampi',
        'product_description' => 'Shrimp Scampi',
        'qty' => 100,
        'price' => 62.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/shrimp_scampi.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Smoked BBQ Brisket',
        'product_description' => 'Smoked BBQ Brisket',
        'qty' => 75,
        'price' => 85.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/smoked_bbq_brisket.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Southern-Style Chicken Biscuit',
        'product_description' => 'Southern-Style Chicken Biscuit',
        'qty' => 80,
        'price' => 79.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/southern_style_chicken_biscuit.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Spicy Buffalo Wings',
        'product_description' => 'Spicy Buffalo Wings',
        'qty' => 80,
        'price' => 79.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/spicy_buffalo_wings.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Spicy Jalapeño Burger',
        'product_description' => 'Spicy Jalapeño Burger',
        'qty' => 80,
        'price' => 45.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/spicy_jalapeno_burger.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Spicy Moroccan Lamb Chops',
        'product_description' => 'Spicy Moroccan Lamb Chops',
        'qty' => 80,
        'price' => 78.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/spicy_moroccan_lamb_chops.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Spicy Tuna Roll',
        'product_description' => 'Spicy Tuna Roll',
        'qty' => 80,
        'price' => 87.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/spicy_tuna_roll.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Spinach and Feta Stuffed Chicken',
        'product_description' => 'Spinach and Feta Stuffed Chicken',
        'qty' => 80,
        'price' => 63.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/spinach_and_feta_stuffed_chicken.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Stuffed Bell Peppers with Ground Turkey',
        'product_description' => 'Stuffed Bell Peppers with Ground Turkey',
        'qty' => 80,
        'price' => 52.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/stuffed_bell_peppers_with_ground_turkey.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Tempura Shrimp Roll',
        'product_description' => 'Tempura Shrimp Roll',
        'qty' => 80,
        'price' => 61.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/tempura_shrimp_roll.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      [
        'product_name' => 'Teriyaki Chicken Wings',
        'product_description' => 'Teriyaki Chicken Wings',
        'qty' => 80,
        'price' => 76.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/teriyaki_chicken_wings.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],



      [
        'product_name' => 'Teriyaki Glazed Chicken Thighs',
        'product_description' => 'Teriyaki Glazed Chicken Thighs',
        'qty' => 80,
        'price' => 68.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/teriyaki_glazed_chicken_thighs.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],


      [
        'product_name' => 'Teriyaki Pineapple Pleasure',
        'product_description' => 'Teriyaki Pineapple Pleasure',
        'qty' => 80,
        'price' => 77.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/teriyaki_pineapple_pleasure.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],


      [
        'product_name' => 'Thai Red Curry',
        'product_description' => 'Thai Red Curry',
        'qty' => 80,
        'price' => 96.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/thai_red_curry.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],


      [
        'product_name' => 'Vegetarian Pad Thai',
        'product_description' => 'Vegetarian Pad Thai',
        'qty' => 80,
        'price' => 95.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/vegetarian_pad_thai.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],


      [
        'product_name' => 'Veggie Dog with Sauerkraut',
        'product_description' => 'Veggie Dog with Sauerkraut',
        'qty' => 80,
        'price' => 93.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/veggie_dog_with_sauerkraut.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],


      [
        'product_name' => 'Veggie Extravaganza',
        'product_description' => 'Veggie Extravaganza',
        'qty' => 80,
        'price' => 45.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/veggie_extravaganza.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],


      [
        'product_name' => 'Veggie Roll',
        'product_description' => 'Veggie Roll',
        'qty' => 80,
        'price' => 78.99,
        'star' => 4.6,
        'time_value' => 150,
        'product_image' => 'storage/products/veggie_roll.jpg',
        'category_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Meat Feast pizza',
        'product_description' => 'Meat Feast pizza',
        'qty' => 150,
        'price' => 25.80,
        'star' => 4.3,
        'time_value' => 60,
        'product_image' => 'storage/products/meat_feast_pizza.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Mediterranean Joy',
        'product_description' => 'Mediterranean Joy',
        'qty' => 130,
        'price' => 43.00,
        'star' => 5.0,
        'time_value' => 50,
        'product_image' => 'storage/products/mediterranean_joy.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Mint Lemonade',
        'product_description' => 'Mint Lemonade',
        'qty' => 160,
        'price' => 23.00,
        'star' => 3.5,
        'time_value' => 50,
        'product_image' => 'storage/products/mint_lemonade.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Mushroom Swiss Delight',
        'product_description' => 'Mushroom Swiss Delight',
        'qty' => 430,
        'price' => 43.00,
        'star' => 4.5,
        'time_value' => 50,
        'product_image' => 'storage/products/mushroom_swiss_delight.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Original Crispy Chicken',
        'product_description' => 'Original Crispy Chicken',
        'qty' => 250,
        'price' => 41.00,
        'star' => 4.5,
        'time_value' => 50,
        'product_image' => 'storage/products/original_crispy_chicken.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Pan Seared Garlic Butter Sirloin',
        'product_description' => 'Pan Seared Garlic Butter Sirloin',
        'qty' => 200,
        'price' => 40.00,
        'star' => 4.5,
        'time_value' => 50,
        'product_image' => 'storage/products/pan_seared_garlic_butter_sirloin.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Pasta Carbonara',
        'product_description' => 'Pasta Carbonara',
        'qty' => 240,
        'price' => 37.00,
        'star' => 4.5,
        'time_value' => 50,
        'product_image' => 'storage/products/pasta_carbonara.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Pepperoni Lovers',
        'product_description' => 'Pepperoni Lovers',
        'qty' => 140,
        'price' => 32.00,
        'star' => 4.5,
        'time_value' => 50,
        'product_image' => 'storage/products/pepperoni_lovers.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Pretzel Bun Dog',
        'product_description' => 'Pretzel Bun Dog',
        'qty' => 260,
        'price' => 33.00,
        'star' => 4.5,
        'time_value' => 50,
        'product_image' => 'storage/products/pretzel_bun_dog.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Quinoa Salad Bowl.jpg',
        'product_description' => 'Quinoa Salad Bowl',
        'qty' => 278,
        'price' => 37.00,
        'star' => 5.0,
        'time_value' => 50,
        'product_image' => 'storage/products/quinoa_salad_bowl.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'product_name' => 'Rainbow Roll',
        'product_description' => 'Rainbow Roll',
        'qty' => 278,
        'price' => 37.00,
        'star' => 5.0,
        'time_value' => 50,
        'product_image' => 'storage/products/rainbow_roll.jpg',
        'category_id' => 4,
        'created_at' => now(),
        'updated_at' => now(),
      ],

    ]);
  }
}
